### ISSUE TITLE
Errors running script.sh

### ISSUE THREAD

**Issue by gdevos010** [pratham16cse/AggForecaster#31]
This project looks exciting, but Im having trouble running the project.  I don't see a requirements.txt or environment.yml, so I did my best to create one.

It looks like there might be some missing files from the project too:

in base_model.py
```
from models import transformer_manual_attn, transformer_dual_attn
ImportError: cannot import name 'transformer_manual_attn' from 'models' (unknown location)
```

Thanks for the help

**Comment by pratham16cse** [comment]
Thank you for your interest in the code.

Running the code does not require the files `transformer_manual_attn` and `transformer_dual_attn`.  I would suggest commenting out this import line and code should work. 

I will fix this import issue in later commits. 

Please let us know if you run into any other issues after this change.

Thanks,
Prathamesh
